### ISSUE TITLE
/dev/nvidia0 not found

### ISSUE THREAD

**Issue by mikelmujika11** [sylvain-prevost/deepstream_wsl#1]
Hi,

I am trying to run DeepStream using WSL2 but in the last step, when running 
`sudo deepstream-test1-app /opt/nvidia/deepstream/deepstream-6.2/samples/streams/sample_720p.h264`
It gives me the following error:
![image](https://github.com/sylvain-prevost/deepstream_wsl/assets/115454804/b4a1d3c0-5af5-4252-91df-97fe31af9141)

How did you manage to put the GPU in the /dev/ directory of Ubuntu?

Thank you!

**Comment by sylvain-prevost** [comment]
Hi, 

simplest first: I would add './' before the app filename 
``` bash
$sudo ./deepstream-test1-app /opt/nvidia/deepstream/deepstream-6.2/samples/streams/sample_720p.h264
```

otherwise:

a/ Did you use the provided example [(wsl prep)](https://github.com/sylvain-prevost/deepstream_wsl/blob/main/Wsl_prep.md) to prepare your wsl instance ?

b/ Within your wsl instance, what do you see when you run the command ?
``` bash
$nvidia-smi
```

Also, this output would be the default one if you did not fully compile/link the gst-nvinfer plugin.
The way I'm testing this repo is:

``` bash
$git clone https://github.com/sylvain-prevost/deepstream_wsl.git
$cd deepstream_wsl
$sudo cp -r sources/ /opt/nvidia/deepstream/deepstream-6.2
```

compile/link gst-nvinfer plugin
``` bash
$cd /opt/nvidia/deepstream/deepstream-6.2/sources/gst-plugins/gst-nvinfer
$sudo make clean install CUDA_VER=11.8 ENABLE_WSL2=1
```

compile/link gst-nvdspreprocess plugin
``` bash
$cd /opt/nvidia/deepstream/deepstream-6.2/sources/gst-plugins/gst-nvdspreprocess
$sudo make clean install CUDA_VER=11.8 ENABLE_WSL2=1
```

compile/link deepstream-test1 application
``` bash
cd /opt/nvidia/deepstream/deepstream-6.2/sources/apps/sample_apps/deepstream-test1
$sudo make CUDA_VER=11.8 ENABLE_WSL2=1
```

start deepstream-test1 application
``` bash
cd /opt/nvidia/deepstream/deepstream-6.2/sources/apps/sample_apps/deepstream-test1
$sudo ./deepstream-test1-app /opt/nvidia/deepstream/deepstream-6.2/samples/streams/sample_720p.h264
```

Let me know if it helps

**Comment by mikelmujika11** [comment]
Hi @sylvain-prevost,

I don't know exactly what I did wrong, but I have done it all over again and followed these last steps as you told me and it works! Thank you very much!
